import * as THREE from "three";
import ranks from "./blueNoise32.bin?arraybuffer&base64";
import temporalRanks from "./blueNoise32x32.bin?arraybuffer&base64";

export const TEMPORAL_SAMPLES = 32;

/** Fixed coverage followed by 32 STBN slices, generated by generate-blue-noise.js. */
export function createBlueNoiseTexture() {
  // Three's WebGPU backend supports R32UI; keep the embedded ranks at 16 bits.
  const data = new Uint32Array(32 * 32 * (TEMPORAL_SAMPLES + 1));
  data.set(new Uint16Array(ranks));
  data.set(new Uint16Array(temporalRanks), 32 * 32);
  const texture = new THREE.DataTexture(
    data,
    32,
    32 * (TEMPORAL_SAMPLES + 1),
    THREE.RedIntegerFormat,
    THREE.UnsignedIntType,
  );
  texture.name = "GaussianSplatBlueNoise";
  texture.needsUpdate = true;
  return texture;
}
