import * as THREE from "three";
import ranks from "./blueNoise64.bin?arraybuffer&base64";

/** Fixed, tileable blue noise generated by scripts/generate-blue-noise.js. */
export function createBlueNoiseTexture() {
  // Three's WebGPU backend supports R32UI; keep the embedded ranks at 16 bits.
  const texture = new THREE.DataTexture(
    Uint32Array.from(new Uint16Array(ranks)),
    64,
    64,
    THREE.RedIntegerFormat,
    THREE.UnsignedIntType,
  );
  texture.name = "GaussianSplatBlueNoise";
  texture.needsUpdate = true;
  return texture;
}
